### ISSUE TITLE
feature request - passing proxy to constructor

### ISSUE THREAD

**Issue by a8775** [Microsoft/typed-rest-client#1]
Now to change eg. proxy you have to set global variable, something like this:
```
process.env.HTTP_PROXY = 'http://127.0.0.1:8080'
```

**Comment by nicojs** [comment]
@a8775 what do you want exactly? It's pretty common to configure the proxy server in your environment.

**Comment by bryanmacfarlane** [comment]
agreed on env

**Comment by nicojs** [comment]
Maybe we could still document that somewhere. It didn't work for me because i had set `http_proxy` instead of `HTTP_PROXY`.
