### ISSUE TITLE
Expose handlers to be used by clients.

### ISSUE THREAD

**Issue by omeshp** [Microsoft/typed-rest-client#10]
We should expose handlers at https://github.com/Microsoft/typed-rest-client/tree/master/lib so that they can be used by consumers. Instead clients currently need to copy them like in vso-node-api https://github.com/Microsoft/vsts-node-api/tree/master/api/handlers and item-level-downloader https://github.com/Microsoft/vsts-rm-extensions/tree/master/ItemLevelDownloader/Providers/Handlers

**Comment by bryanmacfarlane** [comment]
I'll work on this

**Comment by bryanmacfarlane** [comment]
Just merged.  https://github.com/Microsoft/typed-rest-client/pull/13  

Should go out with the next release in a day or so.
