### ISSUE TITLE
http client with binary data response

### ISSUE THREAD

**Issue by Foristkirito** [Microsoft/typed-rest-client#125]
### Environment
Node version: 8.12
Npm version: 6.4.1
OS and version: windows 10
typed-rest-client version: 1.0.11

### Issue Description
I want to receive a file from server. server reponse binary file in body, but http client in this module override all non ascii byte to 65533. I figure out that reponse data is converted to string. Any method to deal with binary data?

**Comment by damccorm** [comment]
When you call GET from the HttpClient, it should return a ```[HttpClientResponse]``` object, which has a property ```message```. If you call ```message.setEncoding(null)```, I believe you should be able to use something like ```message.onData('data', (chunk: Buffer) => {process data here})``` which will avoid the data being converted to a string. message is a ```Http.IncomingMessage``` object which implements node's [readable stream](https://nodejs.org/api/stream.html#stream_class_stream_readable)

**Comment by Foristkirito** [comment]
> When you call GET from the HttpClient, it should return a `[HttpClientResponse]` object, which has a property `message`. If you call `message.setEncoding(null)`, I believe you should be able to use something like `message.onData('data', (chunk: Buffer) => {process data here})` which will avoid the data being converted to a string. message is a `Http.IncomingMessage` object which implements node's [readable stream](https://nodejs.org/api/stream.html#stream_class_stream_readable)

it works, thank you

**Comment by Foristkirito** [comment]
> When you call GET from the HttpClient, it should return a `[HttpClientResponse]` object, which has a property `message`. If you call `message.setEncoding(null)`, I believe you should be able to use something like `message.onData('data', (chunk: Buffer) => {process data here})` which will avoid the data being converted to a string. message is a `Http.IncomingMessage` object which implements node's [readable stream](https://nodejs.org/api/stream.html#stream_class_stream_readable)

it works, thank you
