### ISSUE TITLE
CredentialHandlers add authorization headers to presigned urls

### ISSUE THREAD

**Issue by aasim** [Microsoft/typed-rest-client#126]
### Environment
Node version: v8.12.0
Npm version: 6.4.1
OS and version: Windows 10 Build 17763
typed-rest-client version: 

### Issue Description
We have a scenario where we call the artifacts packaging api to download a package file. This api call redirects you to a presigned blobstore url which has the file contents. The problem I am facing is that the headers from the original api call (including the authorization header) are passed along to the redirected URL, which is presigned in this case, and causes a 401. If I remove the auth header in the redirect logic, it works correctly

### Expected behaviour
CredentialHandlers don't add authorization headers to presigned urls.

### Actual behaviour
CredentialHandlers add authorization headers to presigned urls.

### Steps to reproduce
1. Go to any url that redirects to a presigned url.
2. Enable redirection in the client
3. Response is 401

### Possible fixes
1. The prepareRequest method checks the url path to see if it is preauthorized and disables adding authorization handler.
2. An option is provided for the user to set what urls don't need authentication, using this option, the authhandler logic is completely skipped.

### See also
I checked in these files, there is a TODO to fix https://github.com/Microsoft/typed-rest-client/blob/e8cb7c8490a34073e9744afc995df1a088583492/lib/handlers/basiccreds.ts#L16, perhaps its related to this bug

**Comment by stephenmichaelf** [comment]
Thanks for letting us know @aasim.

@damccorm Can you take a look? Appears that @bryanmacfarlane added the comment so he may have some context.

**Comment by damccorm** [comment]
As best I can tell, its not possible to infer whether a url is presigned based on the response. I don't see a ton of great options to handle this, so I'm mostly inclined to use a whitelistish concept like Aasim suggested,  with pattern matching.
