### ISSUE TITLE
How to leverage keepAlive and reuse connections?

### ISSUE THREAD

**Issue by damadei** [Microsoft/typed-rest-client#132]
### Environment
Node version:  v10.15.0
Npm version: 6.4.1
OS and version: Win 10
typed-rest-client version: 

### Issue Description
I'm making a call to a rest endpoint and no keepalive is in place. Every request opens a new connection. I'd like to understand if keepAlive is supported by the lib and how to force it.

I've tried a global const client but the behavior is the same.

**Comment by damccorm** [comment]
This should be controlled with the ```keepAlive``` option in [```IRequestOptions```](https://github.com/Microsoft/typed-rest-client/blob/f6a2727a2ed8c1f40745c7204bea6648ff673e3b/lib/Interfaces.ts#L53). This can be passed in to the Rest Client [constructor](https://github.com/Microsoft/typed-rest-client/blob/f6a2727a2ed8c1f40745c7204bea6648ff673e3b/lib/RestClient.ts#L39)

**Comment by damccorm** [comment]
I'm going to close since I think the question has been answered. If not, please comment and I'll reopen
