### ISSUE TITLE
Create a form data sample in our samples

### ISSUE THREAD

**Issue by josheplibra** [microsoft/typed-rest-client#138]
I can't send file
Please support it, thank you.
https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects

**Comment by stephenmichaelf** [comment]
If I understand what you're asking for, can't you just write a POST and setup the headers and data in your code? I am not sure this is something we would encapsulate in the library.

**Comment by josheplibra** [comment]
Because using `JSON.stringify` for FormData will return a empty object

Sorry If I don't understand
I see at the file https://github.com/Microsoft/typed-rest-client/blob/master/lib/RestClient.ts
function: create
line 110: `let data: string = JSON.stringify(resources, null, 2);`
`resources` is a `FormData`
and result of the data is a empty object

If you need example, please inform me. I will create
Thank you

**Comment by damccorm** [comment]
I think an example would be helpful. Calling `JSON.stringify` should serialize the object into its key value pairs. Regardless, it seems like you might just be better off using the HttpClient and calling POST

**Comment by bryanmacfarlane** [comment]
That’s correct.  We have an http layer for things like this.  The higher level rest layer is for operating on json resources.  Posting form data is an http concept and not part of RESTful design

**Comment by bryanmacfarlane** [comment]
Danny let’s at a minimum create a form data sample in our samples

**Comment by josheplibra** [comment]
I tried with HttpClient but it still not work
Error: `data.on is not a function`

Because this code at HttpClient.ts

        if (data && typeof (data) === 'string') {
            req.write(data, 'utf8');
        }

        if (data && typeof (data) !== 'string') {
            data.on('close', function () {
                req.end();
            });

            data.pipe(req);
        }

I created example at: https://codesandbox.io/s/4jo72z60v7

**Comment by sanchez** [comment]
I was wondering if this solution has been fixed? I cannot `JSON.stringify` my formdata because it is inspected as empty (something to do with it only containing file data is my guess) and if I try to upload the form data (after casting the type to any) I also get the same issue as mentioned: https://github.com/microsoft/typed-rest-client/issues/138#issuecomment-476533598

Thanks
