### ISSUE TITLE
Remove duplicate definition of IRequestOptions.

### ISSUE THREAD

**Issue by damccorm** [microsoft/typed-rest-client#145]
Somehow this got added to the [RestClient](https://github.com/Microsoft/typed-rest-client/blob/d108cf34f239ebdbb4952184b01dd5d59c7359ab/lib/RestClient.ts#L14) and [Interfaces](https://github.com/Microsoft/typed-rest-client/blob/d108cf34f239ebdbb4952184b01dd5d59c7359ab/lib/Interfaces.ts#L44) code. Even worse, they're different.

We might not be able to kill this immediately due to back compat, but if we major version we definitely should.

**Comment by stephenmichaelf** [comment]
Do we know which one is used more often and where?

FWIW I normally modify the one in the interfaces file.

**Comment by damccorm** [comment]
The one in the interfaces file is used for the client constructors, the one in the RestClient file is used for the operations (get/post/etc...). They're both exported though

**Comment by stephenmichaelf** [comment]
Maybe having two isn't terrible and we just need to rename.

**Comment by damccorm** [comment]
Yeah, definitely an option. I think that might be the best move as well. Regardless, that's still breaking though.

**Comment by bryanmacfarlane** [comment]
I think we should converge to the interfaces one ( that’s official ) and bump by a minor version

**Comment by damccorm** [comment]
I'm not sure I agree - right now they're doing different things (the interfaces one for constructors, the RestClient one for REST operations) and they actually contain a completely non-overlapping set of fields; it seems odd to me to converge to one definition and makes more sense to just rename (I'd be inclined to rename the interfaces one to something like `ClientOptions`).

It also seems to me that your suggested change would be breaking (aside from broken typings) since if we do converge we'd almost certainly want to combine the `additionalHeaders` property from the RestClient version with the `headers` property from the interfaces version.

> that's official

Its unclear to me why - both have been around ~2 years, but the RestClient one is actually slightly older.

**Comment by mmajcica** [comment]
@damccorm what's the status of this? I do have some extra time these days and tackling this would be fun. Is this still of interest? Are any new releases being planned?

**Comment by damccorm** [comment]
@mmajcica I think I'd only want to do this if we major version the library and I don't think we have any compelling reasons to do that right now. I think this one should hang around as a potential enhancement if we do a new major version, but I don't think we should do anything until then.
