### ISSUE TITLE
Add cert support docs

### ISSUE THREAD

**Issue by vmasule** [microsoft/typed-rest-client#146]
Error while calling on-premise endpoint. { Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at TLSSocket._finishInit (_tls_wrap.js:635:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }

**Comment by damccorm** [comment]
I don't think this issue is actually related to this library, so I'm not sure how to best provide guidance. With that said, I think its probably the same issue discussed [here](https://stackoverflow.com/questions/12180552/openssl-error-self-signed-certificate-in-certificate-chain) and the conversation there may be helpful

**Comment by vmasule** [comment]
@damccorm Thanks for quick reply. Actually I have tries with that but unfortunately for development we have to use self sign certificate. I also tried `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`  but that works with `request` package but doesn't works with `typed-rest-client`.

**Comment by vmasule** [comment]
Sorry when `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` it's going through my proxy then I am getting `Error: socket hang up`. I will try fixing this proxy issue. Thanks for your help.

**Comment by vmasule** [comment]
@damccorm How to configure request timeout? Is there any documentation for this lib?

**Comment by damccorm** [comment]
You can use [`socketTimeout`](https://github.com/Microsoft/typed-rest-client/blob/d108cf34f239ebdbb4952184b01dd5d59c7359ab/lib/Interfaces.ts#L46) which is part of `IRequestOptions`. That gets passed in as an [arg to the constructor](https://github.com/Microsoft/typed-rest-client/blob/d108cf34f239ebdbb4952184b01dd5d59c7359ab/lib/RestClient.ts#L41)

**Comment by j0hnwhyte** [comment]
Hi, the README mentions that the self-signed certificate support is part of the library, but I can't even find a mention in the code nor in the examples. Maybe some documentation could be added, thanks.

**Comment by damccorm** [comment]
Sure, it looks like we did add this support a while back. I think all you need to do is include your cert info as part of the requestOptions and pass it to the constructor - https://github.com/Microsoft/typed-rest-client/blob/d108cf34f239ebdbb4952184b01dd5d59c7359ab/lib/Interfaces.ts#L49

I'll look into adding some samples when I get the bandwidth

**Comment by j0hnwhyte** [comment]
Hi, and thanks for the quick answer. To be honest I found the configuration parameter shortly after posting, but still there's no flag to disable the self-signing check. The `ignoreSslError` parameter also seems to do nothing.

**Comment by damccorm** [comment]
Ok, thanks for the update. I think the best path forward is to use the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable.

With all that said, this issue has made it clear that we could definitely use better docs on this, I'm going to rename this issue to reflect that and leave it open until we have that.

**Comment by mmajcica** [comment]
I'm using the ignoreSslError passed in the constructor as part of IRequestOptions parameter and it all works fine.
What would be nice is that the lib could be capable of accessing SChannel as the latest Git client does.
