### ISSUE TITLE
Document releases

### ISSUE THREAD

**Issue by nicojs** [microsoft/typed-rest-client#147]
Hi 👋 . Thanks for maintaining typed-rest-client.

### Issue Description
Please document releases somehow. It is difficult for library users to keep dependencies up-to-date without it.

In #47 it was agreed that releases would be tagged, However, that seems to have stopped? I can't seem to find the 1.4.0 release: https://github.com/microsoft/typed-rest-client/releases

### Expected behaviour

It would be awesome if there was a CHANGELOG.md file or documentation about the releases in github.

### Actual behaviour

No documentation to be found.

**Comment by damccorm** [comment]
Sure, we've gotten out of sync on this but agreed it would be good for us to get back to doing that. I just added a release for 1.4.0, I don't think we need a separate changelog since that info is included in the release info.

**Comment by nicojs** [comment]
As long as it is kept up-to-date I'm happy. ❤️

**Comment by nicojs** [comment]
@damccorm the same thing happened for the 1.5 release this week. Would you mind documenting it 😕

**Comment by damccorm** [comment]
[Done](https://github.com/microsoft/typed-rest-client/releases/tag/1.5.0). Sorry about that.
