### ISSUE TITLE
Using credentials of current user to make REST calls

### ISSUE THREAD

**Issue by dascalos** [microsoft/typed-rest-client#150]
I'm hoping to find a library where I can make rest calls using the credentials of the currently logged in user.  It looks like with this library, I have to send username/password to do NTLM.  

In PowerShell, with Invoke-RestMethod I can use -UseDefaultCredentials to achieve this. 

Is this possible with this library, or some other node library?  Thank you.

**Comment by damccorm** [comment]
As far as I know, Node doesn't have a concept of the currently logged in user/credentials. So I don't think so

**Comment by dascalos** [comment]
Thanks for the response Danny.  Prefer writing TypeScript to PowerShell, so I was hoping something existed.
