### ISSUE TITLE
HTTP Stream Broken By NTLM Authentication 

### ISSUE THREAD

**Issue by sylvanaar** [microsoft/typed-rest-client#151]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/typed-rest-client/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/typed-rest-client/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 10.11.0
Npm version: 6.7.0
OS and version: Mac OSX 10.14.4
typed-rest-client version: 1.2.0

### Issue Description
NTLM Authentication does not work

### Expected behaviour
With NTLM authentication, API calls should succeed

### Actual behaviour
With NTLM authentication, the application build using `azure-devops-node-api` exits when performing an API Call

### Steps to reproduce
1. Use NTLM authentication with `azure-devops-node-api`
2. Call any api

### Logs
I have observed that typed-rest-client consumes the api call response instead of allowing the client to consume it itself.

I have observed removing the code to consume the body does remedy the issue for me

```Typescript
    public handleAuthentication(httpClient: ifm.IHttpClient, requestInfo: ifm.IRequestInfo, objs): Promise<ifm.IHttpClientResponse> {
        return new Promise<ifm.IHttpClientResponse>((resolve, reject) => {
            const callbackForResult = function (err: any, res: ifm.IHttpClientResponse) {
                if (err) {
                    reject(err);
                }
                // We have to readbody on the response before continuing otherwise there is a hang.
                res.readBody().then(() => {  // REMOVE call to readBody, and just call resolve
                    resolve(res);
                });
            };

            this.handleAuthenticationPrivate(httpClient, requestInfo, objs, callbackForResult);
        });
    }
```

**Comment by vKarter** [comment]
Please fix it, we really need it :)

**Comment by vKarter** [comment]
Removed 
`res.readBody().then(()` =>
               resolve(res);
                });`
and leave only resolve(res) helps!
