### ISSUE TITLE
If userAgent is null or not provided it is still added to the headers

### ISSUE THREAD

**Issue by etay2000** [microsoft/typed-rest-client#154]
The 'userAgent' param is set in the headers even if it is null or undefined. I would have expected the behavior to be to conditionally add the header only if it is not null.

**Comment by damccorm** [comment]
The userAgent is a [required field](https://github.com/microsoft/typed-rest-client/blob/5eb9c90a50c730b0c21b78f50e1eb903aa7e8f47/lib/HttpClient.ts#L105) so we should be able to assume that it won't be null/undefined. What's the use case where this is causing problems?

**Comment by etay2000** [comment]
I was unable to make calls to a REST service that does not include 'user-agent' in it's 'Access-Control-Allow-Headers' options. 
"(Reason: missing token ‘user-agent’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel)"

**Comment by damccorm** [comment]
That makes sense. Maybe we can change the signature to accept `string | undefined`. Then below we can check:
```
if(userAgent === undefined) {
   don't pass agent
} else {
   do pass agent
}
```

That way we maintain back compat for `''`, but allow for this scenario - does that seem right?

**Comment by etay2000** [comment]
LGTM

**Comment by stephenmichaelf** [comment]
@jtpetty could you take a look at this and make sure it's good/add tests? Thanks!
