### ISSUE TITLE
Removing underscore dependency?

### ISSUE THREAD

**Issue by jokecamp** [microsoft/typed-rest-client#157]
Would you be open to removing the underscore dependency or consider a PR for removing it?

I only see references to it in [ntlm.ts](https://github.com/microsoft/typed-rest-client/blob/master/lib/handlers/ntlm.ts) and it is mostly the functions extend and omit.

**Comment by stephenmichaelf** [comment]
@jokecamp Is there a specific reason?

For the ntlm code we are generally apprehensive to make modifications unless it's necessary as it's high risk/time consuming to test.

**Comment by jokecamp** [comment]
Understood. Just curious because I have a use case for deploying as small a project as possible. I know it could be viewed as over-optimization or extra work.

**Comment by stephenmichaelf** [comment]
Yeah it looks like its about 112KB for the underscore module.

I would say given the risk/reward we wouldn't make the change at this time.

Thanks for your understanding!
