### ISSUE TITLE
can not upload local file to the endpoint

### ISSUE THREAD

**Issue by FuadAbuSameer** [microsoft/typed-rest-client#158]
### Issue Description
Im my normal curl command  i use the option -F "file=@\"test-results.xml\" to upload file to the endpoint (attach a file to jira ticket). Is this possible using this client

**Comment by damccorm** [comment]
Sure - you can see what curl is doing [here](https://curl.haxx.se/docs/httpscripting.html#File_Upload_POST), but basically its just sending a POST with a form-data content type, so you should be able to do the same thing with this library. We have an open enhancement to add an example of this (#138), but in the meantime you can read up on structuring the request here - https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4

**Comment by jtpetty** [comment]
Closing since the question appears to be addressed. Please feel free to open a new issue if it is not addressed.
