### ISSUE TITLE
Add back NTLM

### ISSUE THREAD

**Issue by stephenmichaelf** [Microsoft/typed-rest-client#16]

**Comment by bryanmacfarlane** [comment]
Support was lost in latest version ...

**Comment by peterblazejewicz** [comment]
Do you mean adding it back via NPM? #22

**Comment by bryanmacfarlane** [comment]
No, I mean in the current version of this library ntlm support is not wired up because we switched to async await and we needed to convert some of the callback code to promises.  There's no artificial constraint that it's done via an npm package which also carries an unneeded and couple http library.

**Comment by bryanmacfarlane** [comment]
More info - httpclient used to be part of node api.  ntlm was added here

https://github.com/Microsoft/vsts-node-api/pull/43/files#diff-a218a7865550fc62c59bb408113064f3

We broke http client out so it can be used in many of our other libs like our tool lib.  When we broke it out, we made it fully async await and ditched call backs.  There was a TODO into this code to re-introduce it but with promises/async/await.   So the handler signature needs to change.  It's one of the things that we're waiting for to release this.  We want that interface to settle.

**Comment by bryanmacfarlane** [comment]
ready for review?

**Comment by stephenmichaelf** [comment]
Not yet. My fix didn't work. I found any other network traffic analyzer and I'm going to try and compare the working vs not working versions. The NTLM strings seem to be generated fine and the steps are all happening. I think it's an issue with adding/removing headers(joining objects incorrectly) or with reusing the connection. Continuing to dig.

**Comment by stephenmichaelf** [comment]
There is a very ugly branch pushed up with a bunch of logging and stuff that I've been testing on.

**Comment by bryanmacfarlane** [comment]
Done and released in latest 1.0.6
