### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by parkerault** [microsoft/typed-rest-client#164]
First of all, thanks for open sourcing this project! I'm just curious what the status of this project is. Is it still being actively maintained? I need to pick a type-safe rest client library for all of our team's SPA projects, and I don't want to use something that's just a wrapper around an older JS library with layers and layers of abstraction. I've been working on a prototype with this library, but the documentation is so sparse I've just been reading the source to learn how to use it. I can see some activity, but there are a few PRs that seem to be getting stale and I don't see any plans for more comprehensive documentation, so I'd like to know if this project is planned to be actively maintained in the future. Is it intended for public consumption, or is it something that's just used internally at MS?

**Comment by bryanmacfarlane** [comment]
Yes, it's maintained and actively being used (and depended upon) in many of the azure pipelines tasks, packages and tools.

**Comment by parkerault** [comment]
Holy crap, that was fast! Thanks for answering! :)

**Comment by bryanmacfarlane** [comment]
:)
