### ISSUE TITLE
Consider Certs In NODE_EXTRA_CA_CERTS

### ISSUE THREAD

**Issue by Jacksondr5** [microsoft/typed-rest-client#166]
## Feature Request
Consider certificates referenced by [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file)
 
## Impacted Code
https://github.com/microsoft/typed-rest-client/blob/c99dbbeba106d4ca59b62a320923eed9b9a6c223/lib/HttpClient.ts#L124-L142
 
A check for the env variable should probably happen around here.  I'm not sure if it would be better to have the ICertConfiguration options merge with anything found in the environment variable or just overwrite the environment variable in favor of the supplied certs.
 
## Use Case
As the [node PR](https://github.com/nodejs/node/pull/9139) explains, self-signed certs are commonly used in closed environments.  

My organization has recently encountered this problem with several TFS extensions.  Using the environment variable solved the problem when extensions were using node HTTP clients, but there are a few extensions that use this library and do not surface a way for us to provide certs [example from NuGetToolGetter](https://github.com/microsoft/azure-pipelines-tasks/blob/33f86f159d78383f8b9fd3ded7b88930b592615e/Tasks/Common/packaging-common/nuget/NuGetToolGetter.ts#L141-L144)

I'm happy to take a stab at it if desired.

**Comment by jtpetty** [comment]
@Jacksondr5 - I think the issue is that by default, the agent uses Node 6 and NODE_EXTRA_CA_CERTS was added in Node 7.3.

Can you try setting the environment variable AGENT_USE_NODE10=true for your job and then try using the NODE_EXTRA_CA_CERTS variable?

**Comment by Jacksondr5** [comment]
@jtpetty Thanks for the reply.  We'll try that environment variable out and let you know how it works

**Comment by Jacksondr5** [comment]
@jtpetty Unfortunately, that didn't seem to have any effect.  We're still seeing certificate errors.

**Comment by jtpetty** [comment]
@mjroghelia - Can you take a look at this one?
