### ISSUE TITLE
303 Redirect Failure

### ISSUE THREAD

**Issue by nitish-patel** [microsoft/typed-rest-client#171]
An issue where 303 SeeOther redirects weren't being followed had been raised and resolved in 2018 - https://github.com/microsoft/typed-rest-client/pull/75

But I'm finding that Rest Client requests I make that involve 303 redirects are coming back as failed requests as opposed to them being followed automatically.

**Comment by damccorm** [comment]
A couple questions:
1) What version of the library are you using?
2) Could you share a repro? Our tests seem to be working fine here, so I'm able to use those to get a repro that works as expected with a 303
3) Could you try hitting `'https://httpbin.org/redirect-to?url=https%3A%2F%2Fhttpbin.org%2Fget&status_code=303'` and seeing if it redirects correctly in that case?
