### ISSUE TITLE
Support adding query parameters

### ISSUE THREAD

**Issue by bbenoist** [microsoft/typed-rest-client#172]
I found no _official_ way to pass query string parameters in a RestClient request.

I would have expected something like:

```ts
const options = {
  queryParameters: {
    lang: "en",
    terms: ["foo bar", 4.2, "baz"]
  }
}
const response = await restClient.get<ISomeResponse>("/search", options);
```

where queryParameters would be of type:

```ts
undefined | { [name: string]: string | number | (string | number)[] }
```

Of course, `typed-rest-client` would have the responsibility of transforming queryParameters to a proper URL query parameter in the correct format.  
e.g. `{ lang: "en", terms: ["foo bar", 4.2, "baz"] }` would become `?lang=en&terms=foo%20bar+4.2+baz` in the corresponding request URL.

Am I missing something? 🤔

**Comment by hamzahejja** [comment]
@stephenmichaelf I'm willing to pick up this issue and work on it, I have read the Contribution guide but needed to ask, should I be added/identified as Contributor to push to the remote origin (Or else i'd receive 403 error or **Access Denied**

**Comment by damccorm** [comment]
@hamzahejja for security reasons we probably can't give you contributor access, but you can create a pull request from a fork - see instructions at https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by hamzahejja** [comment]
@damccorm I see, will do that then, Thanks!

**Comment by bbenoist** [comment]
@hamzahejja Thanks for your work 😃 

@damccorm Can we close this issue?
