### ISSUE TITLE
Update `tunnel` dependency

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/typed-rest-client#177]
### Issue Description
`typed-rest-client` [pins to version `0.0.4` of `tunnel`](https://github.com/microsoft/typed-rest-client/blob/master/package.json#L43).

`tunnel`'s [current latest is `0.0.6`](https://www.npmjs.com/package/tunnel). In `0.0.6` they started excluding their tests ([which includes a ton of `.pem`s](https://github.com/koichik/node-tunnel/tree/master/test/keys)) from the npm package.

Can you switch to this newer version so that you don't redistribute all these `.pem`s and tests? It causes things like credential scanners to go off do to these existing.

### Expected behaviour
`v0.0.6` of the `tunnel` package.

### Actual behaviour
`v0.0.4` of the `tunnel` package with a bunch of test files.

**Comment by jalajmsft** [comment]
+1 facing this issue in azure pipeline tasks. [Reference link](https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1626713)

**Comment by AnthonyDiSanti** [comment]
Can this issue be closed now that #195 has been merged?
