### ISSUE TITLE
I cannot launch the sample provided

### ISSUE THREAD

**Issue by maxperga** [Microsoft/typed-rest-client#2]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Massimo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.5.0
3 info using node@v6.10.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle typed-rest-client@0.10.0~prebuild: typed-rest-client@0.10.0
6 silly lifecycle typed-rest-client@0.10.0~prebuild: no script for prebuild, continuing
7 info lifecycle typed-rest-client@0.10.0~build: typed-rest-client@0.10.0
8 verbose lifecycle typed-rest-client@0.10.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle typed-rest-client@0.10.0~build: PATH: C:\Users\Massimo\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\andrei\typed-rest-client\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Hewlett-Packard\SimplePass\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\Massimo\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Windows Phone TShell\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\Massimo\.dnx\bin;C:\Users\Massimo\AppData\Local\Code\bin;C:\Program Files (x86)\Microsoft VS Code\bin;c:\Users\Massimo\AppData\Local\Android\sdk\platform-tools;C:\Users\Massimo\Downloads\watchman;C:\Users\Massimo\AppData\Local\Microsoft\WindowsApps;C:\Users\Massimo\AppData\Roaming\npm;C:\maven\bin;C:\OpenSSL-Win64\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
10 verbose lifecycle typed-rest-client@0.10.0~build: CWD: C:\andrei\typed-rest-client
11 silly lifecycle typed-rest-client@0.10.0~build: Args: [ '/d /s /c', 'node make.js build' ]
12 silly lifecycle typed-rest-client@0.10.0~build: Returned: code: 1  signal: null
13 info lifecycle typed-rest-client@0.10.0~build: Failed to exec build script
14 verbose stack Error: typed-rest-client@0.10.0 build: `node make.js build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Massimo\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Massimo\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid typed-rest-client@0.10.0
16 verbose cwd C:\andrei\typed-rest-client
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Massimo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 verbose node v6.10.2
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 1
23 error typed-rest-client@0.10.0 build: `node make.js build`
23 error Exit status 1
24 error Failed at the typed-rest-client@0.10.0 build script 'node make.js build'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the typed-rest-client package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node make.js build
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs typed-rest-client
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls typed-rest-client
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

Here is my GIT SHA:
C:\andrei\typed-rest-client>git log
commit f4861975828a453ca6d6ca4abc94ef2dcefc1416
Author: Bryan MacFarlane <bryanmac@microsoft.com>
Date:   Tue Mar 28 16:30:56 2017 -0400

    added options request

**Comment by bryanmacfarlane** [comment]
What version of node?
Did you do npm install before running npm run build?

**Comment by bryanmacfarlane** [comment]
I still can't repro.  Can you answer the questions above?

Please retry with latest code, node and read contribution guide.  If you're still blocked, we can re-open and dig further.
