### ISSUE TITLE
Could not get some REST API data because "A 404 will not throw but the result object will be null and the result statusCode will be set"

### ISSUE THREAD

**Issue by bbenoist** [microsoft/typed-rest-client#202]
### Issue Description

As of now, the documentation (and the corresponding code) states that for the REST client:

> A 404 will not throw but the result object will be null and the result statusCode will be set.

Because of this design, I couldn't get some information returned by a REST API which I don't own.

### Expected behaviour

I expect the result object to be null only if the response object is not valid JSON.

### Actual behaviour

The result object is null even if the REST server returned some data (actually, some details about why it couldn't find the resource).

### Steps to reproduce

With `RestClient`, call a REST service which returns both some data and a 404 status code.

**Comment by celcius112** [comment]
I agree with @bbenoist, without a result we do not have access to the actual error message returned with the 404.

**Comment by bbenoist** [comment]
@bot It's not stale, it's just that we need someone to work on it 😕
