### ISSUE TITLE
"TypeError: Unknown encoding: us-ascii" on HttpClientResponse.readBody()

### ISSUE THREAD

**Issue by issacnitin** [microsoft/typed-rest-client#203]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/typed-rest-client/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/typed-rest-client/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: v8.16/v6 LTS
Npm version: 6.9.0
OS and version: Windows 10
typed-rest-client version: 1.7.2

### Issue Description
When the response header has content-type as us-ascii, typed-rest-client fails to parse the body and throws error. Seem to have come from this PR: https://github.com/microsoft/typed-rest-client/commit/1c1b04ba4a4631dc9d352f8c208a4f112213ccda where Buffer.from() started using encoding type. This is being observed after upgrading to 1.7.2 from 0.12.0

### Expected behaviour
The body should be read regardless of encoding from server

### Actual behaviour
.readBody() threw error

**Comment by bishal-pdMSFT** [comment]
@damccorm can you please look at this issue. This is blocking rollout of a fix present in latest version of typed-rest-client.
