### ISSUE TITLE
Support using in a web page

### ISSUE THREAD

**Issue by baxevanis** [Microsoft/typed-rest-client#21]
https://github.com/Microsoft/typed-rest-client/blob/7ce1f4fe3407900f98a23568c7001c9c8fb23468/lib/HttpClient.ts#L11

Sorry if this is the wrong place to add this but when I am trying to use the library in a project I am getting an error saying that the http.globalAgent is undefined.
At that point http.Agent is available but for some reason not the globalAgent.
Commenting this out or setting the maxSockets in the Agent seems to work properly
`http.Agent.maxSockets = 100;`

Sorry but I was not able to get more info out of the documentation and ensured that I have the latest node and everything.

Even though npm run build and npm run test seems to work without any issues.

Here is a small sample of how I tried to use the library
```
import * as rm from 'typed-rest-client/RestClient';

interface Student {
    message: string
};

async function runSample() {
    let restc: rm.RestClient = new rm.RestClient('rest-samples', 'https://sample-api.dev');

    let res: rm.IRestResponse<Student> = await restc.get<Student>('/ping');

    console.log(res.statusCode);
    console.log(res.result);

    console.log('aha');
}

runSample();

```

The final file is complied with webpack

and I just include the final .js file into the html sample page where I get the error about the http.globalAgent.

Is there a specific reason why you setup the maxSocket at that point and not further down the code like you do for the httpProxy?

Hope the above makes sense.
For any clarifications plz let me know

If this does not make sense or you believe it is irrelevant then plz close it 

Thank you

**Comment by peterblazejewicz** [comment]
> http.globalAgent is undefined

What's your local Node JS version?

**Comment by bryanmacfarlane** [comment]
I will take a look at this.

**Comment by baxevanis** [comment]
Oh sorry thought I had add that :/
`node -v` > `8.9.1`

And here are the dependencies I have (some might not be required as I was trying to resolve the issue and was not sure if I was missing anything!
```
  "dependencies": {
    "@types/jquery": "^3.2.16",
    "@types/node": "^8.0.53",
    "node": "^9.2.0",
    "ts-loader": "^3.1.1",
    "typed-rest-client": "^0.12.0",
    "typescript": "^2.6.1",
    "webpack": "^3.8.1"
  }
```

**Comment by bryanmacfarlane** [comment]
hmmm.  I can't repro and global agent has been there forever

https://nodejs.org/api/http.html#http_http_globalagent

I'll try your sample.  Did you create a server @ https://sample-api.dev/ping that returns a resource?

**Comment by bryanmacfarlane** [comment]
Also, I see you're trying to use this library in a web page?  Right now, it's only supported to use within a node app.  Perhaps that's why?

**Comment by baxevanis** [comment]
Yes this is a demo api server that returns a json response.
And yes I am trying to use the lib on a web page!

OK this is why then! 

Thank you for clarifying and looking into this

**Comment by bryanmacfarlane** [comment]
Please create an issue tagged with enhancement to suggest making it work from a web page.  For now, I will update the docs / readme to make it clearer that it's only supported within node app.

Would be nice though so I'll look into it :)

**Comment by bryanmacfarlane** [comment]
morphed this task.  Thanks for the feedback.

**Comment by johndouglascm** [comment]
Thanks for your contributions.
I hit this as well - maybe for the same naïve reason.
I'd like fork and build an http client (typed and in typescript) that can (via rollup) transpile down *and* be node compatible.  Write once, run everywhere.  ;)  

My efforts floundered on configuring rollup with plugins to pull the node globals along.

**Comment by bryanmacfarlane** [comment]
@baxevanis or @johndouglascm - we do take contributions.  even if you don't complete the contribution, outlining your process / requirements (webpack) etc... would help whoever does the work.  Also, if you had partial work completed, referencing those from a fork would help whoever picks up the work.

**Comment by bryanmacfarlane** [comment]
@baxevanis - we eliminated the globals usage in the most recent version - 1.0.2 (npm install typed-rest-client@preview).

Does that version work for you?

**Comment by sinmaniphel** [comment]
I've had the issue an can provide an explanation as to why the globalAgent property of the http module is not present in the browser.
This is not directly linked to the nodeJs version. 

When using Webpack or Browserify, some core node modules are not natively included, and are replaced by those in
https://github.com/webpack/node-libs-browser

to wit, the http module is actually
https://github.com/jhiesey/stream-http

I suppose the browser being a default agent in itself with properties set by user preferences, such a property would be redundant, or something like that. 

I strongly support this enhancement. Totally eliminating the globals may not be mandatory, if you had a good reason to set them in a non browser environment. A check should be sufficient.

As is, commenting the line works well for me for now.
Awaiting the preview version to become stable.

Thanks for the good work ;)

**Comment by baxevanis** [comment]
Sorry for the late response.
I finally found some time to test the new version and it works like a charm!!!
I've replaced the previous library I was using and from 2.21mb now the final file went down to 408k!!

Thank you!!

**Comment by bryanmacfarlane** [comment]
@baxevanis - Awesome!  we're just waiting on ntlm issue then we will release.  The preview outside of that is solid.

If you ever have time to do a PR on a markdown file for using it in a web page, that would be awesome.  But I'll get to it if you don't :)

Thanks

**Comment by bryanmacfarlane** [comment]
Closing since it works now
