### ISSUE TITLE
Environment variable "NO_PROXY" with wildcard causes HttpClient constructor failure

### ISSUE THREAD

**Issue by tuwrraphael** [microsoft/typed-rest-client#215]
### Environment
Node version: 10.13.0
Npm version: 6.4.1
OS and version: Windows Server 2012 R2
typed-rest-client version: 1.7.3

### Issue Description
Some environments define the environment variable `NO_PROXY` to bypass proxy servers, which the `HttpClient` of this package respects. It is allowed to set wildcard domains in this environment variable like `*.microsoft.com`, altough not every client must respect them. However the `HttpClient` constructor crashes when environment variables like these are present.

### Expected behaviour
The `HttpClient` should construct normally.

### Actual behaviour
The `HttpClient` constructor throws an Exception:
Invalid regular expression: /*microsoft.com/: Nothing to repeat

### Steps to reproduce
1. Set an environment variable like `NO_PROXY = microsoft.com,*.microsoft.com`
2. Construct a `HttpClient`

### Additional Info
This problem caused our Azure DevOps Release Pipeline to crash which tried to deploy an App Service to Azure using the `AzureRmWebAppDeploymentV4` Task. The task already crashes when importing its (js) dependencies, so it was a little complicated to find the source of this error to be this package 😉

**Comment by tuwrraphael** [comment]
I've created a fix for this problem which escapes the wildcard for the `RegExp` constructor.

**Comment by tuwrraphael** [comment]
I've created a fix for this problem and I'm still expecting it getting merged, therefore it is not actually stale.

**Comment by calebcartwright** [comment]
Sorry for the bump, but can we get an update on this? This lib is used within the Azure Pipelines ecosystem, and has started causing lots of challenges for us with our self-hosted agents.

cc'ing some folks based on semi-recent merges/commits @mastrzyz @damccorm @stephenmichaelf

**Comment by tuwrraphael** [comment]
Thanks @calebcartwright for the support. Some of our self-hosted agents also still fail when executing azure web app deployments because of this. I think my PR is neat and small enough to review/merge.
I can for example rebase it on current master but I need some feedback here in order to take further actions.

**Comment by HonzaMac** [comment]
This bug is happening also in my company proxy settings. It would be great to fix this as it blocks us from using https://github.com/stryker-mutator/stryker/issues/2731
