### ISSUE TITLE
Feature request: Handle response decoding (JSON.parse) in a handler so you can provide your own

### ISSUE THREAD

**Issue by air2** [microsoft/typed-rest-client#241]
### Issue Description
I have to a rest API (well some company provides a rest API and I have to talk to it) which has some long history so some calls do not send back json, but send back XML. Which screws the parsing. If I only could provide my own `body->json-object` handler it would be great. the default handler could implement the same logic as is in it right now.

Is this a direction this project would take? If so I would maybe able to supply some code to implement this.

**Comment by air2** [comment]
This is not stale

**Comment by EpicKris** [comment]
Bump.
