### ISSUE TITLE
Humbly asking for a new release

### ISSUE THREAD

**Issue by amotl** [microsoft/typed-rest-client#246]
Dear @damccorm, @bryanmacfarlane and contributors,

first things first: Thanks a stack for conceiving this excellent package.

Through https://github.com/eskatos/gradle-command-action/issues/22, we became aware that 5f16b0dc3 coming from #194 might fix a deprecation warning observed by many people using the Gradle Command GitHub Action.

Some people also claim that this would occasionally crash the gradle process. While I can't confirm this, I still would like to humbly ask if you could publish a new release based on the current state of the code base if you don't have any objections?

As I can see, the most recent official release [1] happened about three months ago, so it might not include 5f16b0dc3 yet?

Keep up the spirit and with kind regards,
Andreas.

P.S.: At the same time, can I also ask you to start adding tags to the repository again? I see that the most recent tag is 1.5.0 while the most recent release on npmjs.com is 1.8.0 already.

[1] https://www.npmjs.com/package/typed-rest-client

**Comment by damccorm** [comment]
Sure, pushed and tagged!

**Comment by amotl** [comment]
Hi Danny,

that was really quick, thank you so much!

With kind regards,
Andreas.
