### ISSUE TITLE
Support for query parameters in `create`, `update` and `replace` calls

### ISSUE THREAD

**Issue by gugahoi** [microsoft/typed-rest-client#257]
### Issue Description

I can see support for query parameters were added to the RestClient as per issue #172 however they were only added to some calls but not all. Is there a reason for that? It seems misleading that the library accepts query parameters for other calls however simply drops them without error or warning. 

As an example, when trying to query `googleapi` with a post request, it requires the `apikey` to be supplied as a query parameter. This currently seems to not be possible through the RestClient unless I specify the parameters as part of the URL.

### Expected behaviour

Query parameters should not be dropped from any request or the compiler should complain if they are not supported.

### Actual behaviour

`create`, `update` and `replace` requests do not honor the query parameters however they accept it without compilation errors.

### Steps to reproduce

1. Make the following request

```
const client = new rm.RestClient('', 'https://test.com')
const options = {
  queryParameters: {
    lang: "en",
    terms: ["foo bar", 4.2, "baz"]
  }
}
const response = await client.create('path', null, options)
```
2. Notice that the query parameters are missing from the request (however you can introspect it)

**Comment by ajuanjojjj** [comment]
Hi; I submitted a pull request for this a while ago, but seems like the tests were failing at that time so I assume that's the reason it got ignored. Its passing all tests just fine now, so it'd be nice if it got merged 

The PR: https://github.com/microsoft/typed-rest-client/pull/245

**Comment by ajuanjojjj** [comment]
The issue is still reproducible, and the linked PR that fixes it hasn't been reviewed. For anyone encountering this, you can fix it on your project using [patch-package](https://www.npmjs.com/package/patch-package), and adding `, (options || {}).queryParameters` to the URLs on the methods yourself.

**Comment by scerdal** [comment]
We're facing the same issue and would like to have the query parameters passed in to the other HTTP methods besides GET. I can add an updated PR if it will be considered

**Comment by ajuanjojjj** [comment]
> @DenisRumyantsev We're facing the same issue and would like to have the query parameters passed in to the other HTTP methods besides GET. I can add an updated PR if it will be considered

After almost losting it because of github's "Sync Fork"'s button, I just updated the branch and posted a new PR
Fingers crossed!

**Comment by scerdal** [comment]
@ivanduplenskikh will you guys take a look at this PR as well?
