### ISSUE TITLE
Cannot use the library on linux

### ISSUE THREAD

**Issue by nicojs** [Microsoft/typed-rest-client#26]
I cannot use this library on linux, because of inconsistent casing of files. Take bearertoken.d.ts as an example, it is importing `'../interfaces`. A file `interfaces.d.ts` does not exist, it should have been including `'../Interfaces'`.

Results in this error:

```
src/client/HttpClient.ts(5,33): error TS2307: Cannot find module 'typed-rest-client/interfaces'.
```

**Comment by bryanmacfarlane** [comment]
I will fix it.

**Comment by nicojs** [comment]
@bryanmacfarlane thanks! Feel free to use my PR 🤝

**Comment by bryanmacfarlane** [comment]
Cool.  Will do.  I'll verify today.
