### ISSUE TITLE
decompressGzippedContent : missing return when rejecting promise

### ISSUE THREAD

**Issue by cgadam** [microsoft/typed-rest-client#278]
Shouldn't this `reject` have a `return` next to it? Otherwise both `resolve` and `reject` gets called leading to unexpected results.

https://github.com/microsoft/typed-rest-client/blob/master/lib/Util.ts#L93

Actually I think this is the reason why this other error gets exposed: https://github.com/microsoft/typed-rest-client/issues/272 instead of bubbling up the actual error from the `zlib` library as part of the promise rejection.

**Comment by anatolybolshakov** [comment]
Hi @cgadam in general this won't lead to issue - since promise object in rejected state can't be moved to resolved.

**Comment by anatolybolshakov** [comment]
@cgadam I'm closing this at the moment since it looks resolved - please let us know if you have any concerns.
