### ISSUE TITLE
Sending body with delete request

### ISSUE THREAD

**Issue by avinashs15** [microsoft/typed-rest-client#281]
Hi,

I was wondering if there is a way to send body with RestClient Delete request.

As of now there's no option to send body with RestClient.del<ResponseType>(resource: string, options?: IRequestOptions | undefined):

**Comment by kuleshovilya** [comment]
We looked into the issue, and currently, we don't consider implementing that, as this is not relevant for most users. We'll keep this request in the backlog, and if we'll see an increase in demand for it, will implement that.
For now, I'll close the ticket, feel free to follow up if you have any questions or ping me at v-ikuleshov@microsoft.com
