### ISSUE TITLE
Possible regression in proxy variable processing

### ISSUE THREAD

**Issue by ssaarinen** [microsoft/typed-rest-client#291]
### Environment
Azure devops pipeline (hosted ubuntu 1604)
typed-rest-client version: 1.8.5

### Issue Description
ContainerStuctureTest task which uses typed-rest-client internally fails with following error:
`##[error]Unhandled: Invalid regular expression: /(?<!\\)([.])(?!\*)/: Invalid group`

ContainerStructureTest needs typed-rest-client to be added manually and only change to the pipeline was that yesterday it used 1.8.4 and today switched to 1.8.5 causing the above error. Forcing version back to 1.8.4 fixed the error.

### Logs
Not much more than the error given is printed when running the task even with diagnostics enabled

**Comment by EzzhevNikita** [comment]
Hi @ssaarinen, seems like the issue is caused by the fact lookbehind constructions are not supported by node 6 which is used by this task. We've deprecated typed-rest-client of 1.8.5 version for now.

**Comment by EzzhevNikita** [comment]
@ssaarinen We have reverted changes (https://github.com/microsoft/typed-rest-client/pull/292) made in 1.8.5 version. So seems like this issue could be resolved.

**Comment by ssaarinen** [comment]
FWIW I think ContainerStructureTest should update it's runtime as node 6 is pretty stale. Also CST task does not even include typed-rest-client directly (which it also should and thus pin the version) but I have to install it manually before running the task. => Lazy me just installed the latest version causing the error.

**Comment by EzzhevNikita** [comment]
@ssaarinen  Yeah, I agree with you about updating the task runtime. In general, we are working on migrating all the built-in tasks to node 10, most of them have already been migrated, but there are some that have not been migrated yet. Unfortunately, my team does not support this particular task, so I suggest you create a ticket in the https://github.com/microsoft/azure-pipelines-tasks/issues repository with the request for updating of runtime for this task.
