### ISSUE TITLE
SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by ivansnek** [microsoft/typed-rest-client#293]
### Environment
Node version: **16.4.2**
Npm version: **6.14.14**
OS and version: **macOS Big Sur 11.3.1**
typed-rest-client version: **1.8.4**

### Issue Description
- Web app using this library as dependency not working on iOS browsers(Chrome, Safari, Brave & Firefox tested)

### Expected behaviour
Dependency work as expected like prior versions

### Actual behaviour
Exception throw: `SyntaxError: Invalid regular expression: invalid group specifier name`

### Steps to reproduce
1. install dependency`typed-rest-client@1.8.4` or above 
2. run locally 
3. Open app on mobile browser on an iOS device
4. Exception thrown

### Logs
![CleanShot 2021-08-17 at 4 59 17](https://user-images.githubusercontent.com/1279062/129806330-c778e4c9-81be-430a-94bb-d79c51b09b47.png)

**Comment by EzzhevNikita** [comment]
@ivansnek Please try to use typed-rest-client@1.8.6, this issue should be fixed there.

**Comment by EzzhevNikita** [comment]
@ivansnek Is your issue resolved? Could we close this item?

**Comment by ivansnek** [comment]
@EzzhevNikita yes is working again, thanks for the update
