### ISSUE TITLE
Remove typings and Index.d.ts

### ISSUE THREAD

**Issue by Dante-101** [Microsoft/typed-rest-client#3]
In the distributed npm package, `Index.d.ts` has `/// <reference path="../typings/index.d.ts" />` which prevents it from compiling. It works fine after I delete the file. Can we remove this?

Also, the documentation encourages installation of `typings` which was deprecated long time back. Can we update it to follow the best practices?

**Comment by bryanmacfarlane** [comment]
I'll update without typings. thx

**Comment by bryanmacfarlane** [comment]
Fixed.  Thanks for reporting
