### ISSUE TITLE
Set PR CI validation

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/typed-rest-client#32]
One yaml file
3 defs (linux, osx and windows).  Use hosted linux, OSX and VS2017 pools

**Comment by bryanmacfarlane** [comment]
add to our teams dashboard

**Comment by stephenmichaelf** [comment]
#44

**Comment by stephenmichaelf** [comment]
YAML file is merged to master and 3 builds are setup. Need verification that the queues are correct.

**Comment by stephenmichaelf** [comment]
Setup on dashboard:

![image](https://user-images.githubusercontent.com/450490/34268191-cae79e50-e64d-11e7-9aa6-27195b5eca46.png)

Triggers setup for master and PR builds.
