### ISSUE TITLE
Discussion: use with fetch API

### ISSUE THREAD

**Issue by jamesarosen** [microsoft/typed-rest-client#341]
### Environment
Node version: 18.x
typed-rest-client version: 1.8.11

### Issue Description
Popular libraries like [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen) and [cache-control-fetch](https://www.npmjs.com/package/cache-control-fetch) rely on the `fetch` API. This API is new in Node 18, but has good polyfill support through [node-fetch](https://www.npmjs.com/package/node-fetch) or [minipass-fetch](https://www.npmjs.com/package/minipass-fetch).

It is currently possible to override `RestClient.client.requestRawWithCallback` to use `fetch`, but the method is complex and the interface between `fetch/Request/Response` and `http/ClientRequest/IncomingMessage` is nuanced. I'd love to see a standard (and well-tested!) community solution for this so we can all get the implementation right.

**Comment by jamesarosen** [comment]
In the meantime, [`scarlett`](https://www.npmjs.com/package/scarlett) is a possible alternative for folks who want a typed fetch-based REST library.

**Comment by DmitriiBobreshev** [comment]
Hi @jamesarosen, thank's for the suggestion, we will take a look what is the best way to implement the solution when we will have enough capacity, but any suggestions, discussions and PRs are welcome!

**Comment by jamesarosen** [comment]
I think the simplest thing would be to add an optional `FetchBasedHttpClient` to this package. Clients would opt into it with:
```ts
import { RestClient, FetchBasedHttpClient } from "typed-rest-client";

const myApi = new RestClient({ client: new FetchBasedHttpClient() });
```
That would require adding an *optional* package dependency on either `node-fetch` or `minipass-fetch`.

Another alternative would be a separate package like `microsoft/typed-fetch-client`. That seems like more overhead than is necessary.
