### ISSUE TITLE
Incorrect header check error while decompressing a response

### ISSUE THREAD

**Issue by sebastien-klima** [microsoft/typed-rest-client#353]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/typed-rest-client/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/typed-rest-client/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: v16.19.0
Npm version: 8.19.3
OS and version: MacBook Pro Ventura 13.0 (22A380)
typed-rest-client version: 1.8.9

### Issue Description
GZIP Compression is enabled on Spring Boot application (embedded server)

Here below the json response served by spring boot endpoint '/api/about' 
`{"application":"xxx","version":"0.0.74-SNAPSHOT","environment":"local","connectedTo":{"application":"xxx","version":"0.0.73-SNAPSHOT","environment":"local","connectedTo":{"application":"xxx","version":"0.0.45-SNAPSHOT","environment":"local"}}}`

Here below a screenshot illustrating the issue on chrome browser
![image](https://user-images.githubusercontent.com/121866146/228308326-482f7408-e606-40d6-a14e-1b75e148013b.png)
 
### Expected behaviour
Should not have exception.

### Actual behaviour
Below error happens and the data cannot be decompressed and consumed by React client application.
index.js:352 Uncaught (in promise) Error: incorrect header check
    at T._handle.onerror (index.js:352:17)
    at d._error (binding.js:283:8)
    at d._checkError (binding.js:254:12)
    at d._after (binding.js:262:13)
    at binding.js:126:10
    at p.run (browser.js:153:14)
    at f (browser.js:123:42)

**Comment by ivanduplenskikh** [comment]
Hi @sebastien-klima thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
