### ISSUE TITLE
Add `EHOSTUNREACH` to `NetworkRetryErrors` list

### ISSUE THREAD

**Issue by adviri** [microsoft/typed-rest-client#372]
Hello,

I have noticed that the `NetworkRetryErrors` list in [lib/HttpClient.ts](https://github.com/microsoft/typed-rest-client/blob/1815244e8f44dad98a63e4a6d637659a8a59cddd/lib/HttpClient.ts#L44).js does not include `EHOSTUNREACH`.

```javascript
const NetworkRetryErrors: string[] = ['ECONNRESET', 'ENOTFOUND', 'ESOCKETTIMEDOUT', 'ETIMEDOUT', 'ECONNREFUSED'];
```

I happened to encounter `EHOSTUNREACH` errors due to temporary network issues. I believe it would be beneficial to include `EHOSTUNREACH` in the `NetworkRetryErrors` list so that requests encountering this error can be retried.

Thank you for your time :)

**Comment by DenisRumyantsev** [comment]
Done, thanks for the suggestion.
