### ISSUE TITLE
Linting and strict compilation

### ISSUE THREAD

**Issue by stephenmichaelf** [microsoft/typed-rest-client#39]
Look at:
- tslint
- tslint-microsoft-contrib
- strict compile settings

**Comment by stephenmichaelf** [comment]
This will be added but we are deferring the work at the moment to focus on higher priorities.

**Comment by nschonni** [comment]
Probably fine to do TSLint for now, but it looks like ESLint may replace it in the future https://eslint.org/blog/2019/01/future-typescript-eslint
