### ISSUE TITLE
Support paths in base url

### ISSUE THREAD

**Issue by torbinsky** [Microsoft/typed-rest-client#4]
Just had a bug that turned out to be caused by the base "url" effectively being a "base domain."

For example, if you set the base url to `http://example.com/common/base/path` and then call a method with a relative path of `/relative/path` the client will end up calling `http://example.com/relative/path`.

From my experience, it's pretty common for REST API's to have a common base url that **includes path elements** and it is also common for client implementations to accept common path elements in the base url.

I think it would be a lot more user-friendly and conventional to support path elements in the base url.

**Comment by bryanmacfarlane** [comment]
Thanks for the feedback.  I'll consider this.

**Comment by kaeedo** [comment]
In my use case, I also need to do this. Would be nice to have as a config option

**Comment by bryanmacfarlane** [comment]
@keedo, PRs are welcome.

**Comment by bryanmacfarlane** [comment]
Note that we're not stripping - the base url is the host portion of the url and then we add the relative paths.  What it should do is if the "base url" has a path portion, it should save that off and then on every request pre-pend to the path given.  Will need a bunch of tests for combinations ...

PRs welcome or I will get to soon.

**Comment by kaeedo** [comment]
Created PR for this: https://github.com/Microsoft/typed-rest-client/pull/23

**Comment by bryanmacfarlane** [comment]
done

**Comment by MadhuvanthG** [comment]
I'm using `1.8.1` and don't see that this issue has been fixed. Do we need to pass an additional param to preserve the path in baseURL? Looking at the code in the mentioned PR, doesn't look like it though.
