### ISSUE TITLE
Please tag released versions

### ISSUE THREAD

**Issue by sinmaniphel** [Microsoft/typed-rest-client#47]
Once again, thanks for your had work on this library :)

# Request
Could you please, prior to publication of this library on NPM, include in your build script (if any) a tagging of the current version in GIT ?

# Purpose
When using a specify published version of your lib, it would be useful to have a tag on the version tree in order to
- Reproduce the build
- Explore the code at that time for debugging purpose
etc.

# How to
There are severall methods, here is one, for example
https://coderwall.com/p/mk18zq/automatic-git-version-tagging-for-npm-modules

Thanks :)

**Comment by stephenmichaelf** [comment]
Thanks for the feedback @sinmaniphel ! We appreciate it. We will have a discussion about this, adding it makes sense to me :) We are planning to release 1.0 soon so it's good timing.

**Comment by bryanmacfarlane** [comment]
Thank you.  

Since we just released 1.0, I started creating a release (and therefore a tag for every release).

https://github.com/Microsoft/typed-rest-client/releases

**Comment by sinmaniphel** [comment]
Kudos ;)

Le mer. 31 janv. 2018 02:56, Bryan MacFarlane <notifications@github.com> a
écrit :

**Comment by per1234** [comment]
Please take another look at this. The tags have not been created for recent releases of the package.

CC: @kirill-ivlev @bryanmacfarlane
