### ISSUE TITLE
RestClient#post?

### ISSUE THREAD

**Issue by preston** [Microsoft/typed-rest-client#61]
Shouldn't RestClient declare a post method? :)

**Comment by bryanmacfarlane** [comment]
The http module does: https://github.com/Microsoft/typed-rest-client/blob/master/lib/HttpClient.ts#L157

 POST is the http implementation of how REST does a create.  So create resource does an http post:  https://github.com/Microsoft/typed-rest-client/blob/master/lib/RestClient.ts#L101
