### ISSUE TITLE
Support IE11 - target es5

### ISSUE THREAD

**Issue by baxevanis** [microsoft/typed-rest-client#62]
Hi again,
this is mainly a question/request.

### Issue Description
We currently use the library for browser usage and as we would like to be able and support IE11 the current npm package is not compatible as the compilation is targeted for es2015.
(The issue is that after compilation the files keep the class references which are not supported by IE11).

### Solution
We have tried to work a solution with that and we have forked and updated the required files to target es5.

Our script works awesome with this change.

You can view the fork and branch here

https://github.com/baxevanis/typed-rest-client/tree/feature/support_es5

Please be aware that we also install the package through npm and github and that is why we had to add some additional configuration in the package.json (prepare and postinstall) to ensure npm can properly install the package.

### Questions
So I have two questions:

1. If we are to make a pull request with the target change to es5, would you consider accepting this change or your script relies on using es2015 explicitly?

2. Can we publish a new npm package ex: typed-rest-client-es5 that will support es5? (by doing this we can clean up the additional changes that are required to install the package from github).

Thank you
Nikolaos

**Comment by stephenmichaelf** [comment]
@bryanmacfarlane

**Comment by stephenmichaelf** [comment]
1. We would not accept a change to target es5, we don't want to change the target for this project.
2. You are welcome to fork and publish any package (it is open source :)) but please do not name it similarly and ensure that there is no user confusion that your forked package is not supported by Microsoft.

Thanks!

**Comment by bryanmacfarlane** [comment]
We're going to take another look at this.

**Comment by bryanmacfarlane** [comment]
I'll investigate

**Comment by baxevanis** [comment]
Hi @bryanmacfarlane 
If there is anything I can do to help out plz let me know!

More than happy to offer any assistance on this

Thank you!

**Comment by damccorm** [comment]
Ok, after talking this over a little more, I think we're going to hold off on this for now. We may move forward with this in the future, but if we do we want to put forth a more focused effort with more testing/sample support. If this is an issue for you right now, we recommend forking this repo and copying over PR #84.
