### ISSUE TITLE
Replace httpbin with nock

### ISSUE THREAD

**Issue by stephenmichaelf** [Microsoft/typed-rest-client#72]
Investigate replacing httpbin requests with Nock.

https://github.com/nock/nock

Would give us more control. Easier to test authentication too?

**Comment by mootrichard** [comment]
I would definitely agree with this. I have been attempting to tinker with removing underscore as a dependency and keep running into issues with running the tests. I keep getting somewhat random 503 errors from httpbin.

**Comment by stephenmichaelf** [comment]
Thanks for the feedback Richard, much appreciated. I was seeing 503s yesterday too.

I will take a look at integrating Nock tomorrow.
