### ISSUE TITLE
No example of how to setup client using proxy

### ISSUE THREAD

**Issue by zielinskikamil** [Microsoft/typed-rest-client#78]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/typed-rest-client/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/typed-rest-client/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 8.9.4
Npm version: 5.6.0
OS and version: MacOS High Sierra
typed-rest-client version: 1.0.9

### Issue Description
I can't configure the proxy. Not sure if there is a bug or if I messed up sth.
Also, my script is run by protractor with a configured proxy

### Expected behaviour
Add example how to use a proxy (and verify it)

### Actual behaviour
I got the following error: 
tunneling socket could not be established, cause=connect ETIMEDOUT ip address:port

### Steps to reproduce
1. setup proxy
2. try to configure HTTPClient to work with this proxy

**Comment by stephenmichaelf** [comment]
Thanks for the feedback @zielinskikamil We will add an example.
