### ISSUE TITLE
REST client needs to expose HEAD

### ISSUE THREAD

**Issue by stephenmichaelf** [Microsoft/typed-rest-client#81]
The HTTP client does, we need the REST one to also. It will be consumed in the node api.

**Comment by stephenmichaelf** [comment]
We are going to handle this in generation for the node api.

**Comment by damccorm** [comment]
@stephenmichaelf Do you think this is worth having for other users of the library? If not I'll close my PR, but its a pretty straightforward change I think.

**Comment by damccorm** [comment]
Ok, that makes sense, I'll close the PR.
