### ISSUE TITLE
Propogate headers in RestClient's IRestResponse

### ISSUE THREAD

**Issue by damccorm** [Microsoft/typed-rest-client#87]
### Environment
Node version: 
Npm version: 8.11.4
OS and version: Windows 10
typed-rest-client version: 1.0.9

### Issue Description
Currently, in RestClient, calls to the public functions all receive a httpm.HttpClientResponse object which contains headers but return a promise of an IRestResponse object which does not contain headers.

### Expected behaviour
IRestResponse should contain headers

### Actual behaviour
IRestResponse only contains information pulled from the result and the status code.

### Steps to reproduce

```
let restc: RestClient = new RestClient('rest-samples', 'httpbin.org/');
let restRes: IRestResponse<Object> = await restc.get<Object>('get');
```
Try to get headers from restRes

**Comment by damccorm** [comment]
@wham any update on this? Are you still looking for a contribution?

**Comment by debben** [comment]
I see a contribution was accepted, but is there any timeline for when this will be released?

**Comment by damccorm** [comment]
@bryanmacfarlane can we release?

**Comment by damccorm** [comment]
Sorry, this slipped through the cracks - it has been published.

**Comment by damccorm** [comment]
Sorry, this slipped through the cracks a little bit - it has been published now.
