### ISSUE TITLE
What use var in es2015?

### ISSUE THREAD

**Issue by Jungwoo-An** [Microsoft/typed-rest-client#89]
I think should use const instead of var.

[ntlm.ts](https://github.com/Microsoft/typed-rest-client/blob/master/lib/handlers/ntlm.ts#L8)

**Comment by damccorm** [comment]
Yeah, both _ and ntlm should probably be const. It won't break anything either way, but its good practice to have them as consts. Do you want to submit a pull request for this?

**Comment by Jungwoo-An** [comment]
Yes. I do
