### ISSUE TITLE
[Feature Request] - Retry support in HttpClient

### ISSUE THREAD

**Issue by asranja** [Microsoft/typed-rest-client#9]
As part of the HttpClient, we were looking for a feature which enables us to retry the Http calls in case of specific errors (ex: 502 Bad Gateway or 504 Gateway Timeout).

**Comment by stephenmichaelf** [comment]
We have tried to be consistent with .NET library implementations. I believe HttpClient does not support retrys, users have to code it themselves. @bryanmacfarlane are you OK staying with .NET on this?

NOTE: We just merged a change to allow redirects for some 3XX codes.

**Comment by stephenmichaelf** [comment]
Discussed offline, we are going to push this to consumers like .NET does. Thank you for the suggestion!
