### ISSUE TITLE
NTLM options need to all be specified

### ISSUE THREAD

**Issue by damccorm** [Microsoft/typed-rest-client#92]
Right now if ntlmHandler's workstation and domain aren't specified, calls to ntlm.createType1Message (and maybe other methods) fail. They work if workstation and domain are specified, even if they're set to empty strings.

Discovered this while investigating https://github.com/Microsoft/azure-devops-node-api/issues/172

FYI - [this](https://github.com/Microsoft/typed-rest-client/blob/c5d6b7f852ddb458a719ee8d9ebd4788f30e923f/lib/opensource/node-http-ntlm/ntlm.js#L62) is where it fails because it tries to call toUppercase on an undefined object

**Comment by stephenmichaelf** [comment]
Are you thinking this might be the reason people are having failures?

**Comment by damccorm** [comment]
Potentially - I was having issues and changing this fixed it for me. I asked about it in the thread yesterday, we'll see what people say. Regardless, probably makes sense to release this patch and upgrade node-api's dependency because this definitely _can_ cause errors.
